---
- name: Setup Hyperion Server
  hosts: hyperion
  pre_tasks:
    # apt housekeeping
    - name: Update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Add hyperion apt gpg key
      apt_key:
        url: https://apt.hyperion-project.org/hyperion.pub.key
        state: present

    - name: Add hyperion repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hyperion.pub.gpg] https://apt.hyperion-project.org/ $(lsb_release -cs) main"
        state: present

    - name: Install hyperion
      apt:
        name:
          - hyperion
        state: latest
    
    - name: verify hyperiond service
      service:
        name: hyperion@root.service
        state: started