---
- name: Add hyperion apt gpg key
  become: true
  apt_key:
    url: "{{ apt_key_url }}/hyperion.pub.key"
    keyring: "{{ keyring }}"
    state: present

- name: Add hyperion repository
  become: true
  apt_repository:
    repo: >
      deb [signed-by={{ keyring }}]
        {{ apt_key_url }}/ {{ ansible_distribution_release | lower }} main
    state: present

- name: Install hyperion
  become: true
  apt:
    name: hyperion

# restart service as the root user
- name: Disable systemd unit @ pi user
  systemd:
    name: hyperion@pi.service
    state: stopped
    enabled: false

- name: Enable systemd unit @ root user
  become: true
  systemd:
    name: hyperion@root.service
    state: started
    enabled: true

- name: verify hyperiond service
  service:
    name: hyperion@root.service
    state: started

- name: Validate connection to hyperion servers
  wait_for:
    host: "{{ ansible_host }}"
    port: 8090
    timeout: 30
    active_connection_states: ESTABLISHED
