---
- name: Disable hyperiond @ root user
  become: true
  systemd:
    name: hyperion@root.service
    state: stopped
    enabled: false

- name: verify hyperiond service is stopped
  service:
    name: hyperion@root.service
    state: stopped

- name: Uninstall hyperion
  become: true
  apt:
    name: hyperion
    state: absent

- name: Remove hyperion apt gpg key
  become: true
  apt_key:
    url: "{{ apt_key_url }}/hyperion.pub.key"
    keyring: "{{ keyring }}"
    state: absent

- name: Remove hyperion repository
  become: true
  apt_repository:
    repo: >
      deb [signed-by={{ keyring }}]
        {{ apt_key_url }}/ {{ ansible_distribution_release | lower }} main
    state: absent
